// Generated by /home/jreidinger/prace/bindgen/clang/find_clang.cr
// DO NOT CHANGE

#define BG_SYSTEM_INCLUDES { "/usr/lib64/clang/7.0.1/../../../include", "/usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7", "/usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/x86_64-suse-linux", "/usr/bin/../lib64/gcc/x86_64-suse-linux/7/../../../../include/c++/7/backward", "/usr/local/include", "/usr/lib64/clang/7.0.1/include" }
