// Generated by /home/jreidinger/bindgen/clang/find_clang.cr
// DO NOT CHANGE

#define BG_SYSTEM_INCLUDES { "/usr/lib64/clang/9.0.1/../../../include", "/usr/bin/../lib64/gcc/x86_64-suse-linux/9/../../../../include/c++/9", "/usr/bin/../lib64/gcc/x86_64-suse-linux/9/../../../../include/c++/9/x86_64-suse-linux", "/usr/bin/../lib64/gcc/x86_64-suse-linux/9/../../../../include/c++/9/backward", "/usr/local/include", "/usr/lib64/clang/9.0.1/include" }
